{% set name = "mtpy-v2" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mtpy-v2-{{ version }}.tar.gz
  sha256: 53e742b711f2973df8d6da033249ca69e65fcd2b2435f5c5f3ab4affca2ae528

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pytest-runner
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base <=3.5.3
    - pyproj
    - configparser
    - mt-metadata
    - mth5
    - pandas
    - geopandas
    - contextily
    - pyevtk
    - loguru

test:
  imports:
    - mtpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MTgeophysics/mtpy-v2
  summary: Python toolkit for standard magnetotelluric data processing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
