{% set name = "mtpy-v2" %}
{% set version = "2.1.0" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c40063e61b2e27678a69f6cd38d6ff6e04df519a31bf82226eb3433a4fd1386a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
  run:
    - python >=3.10
    - configparser
    - contextily
    - geopandas
    - matplotlib-base
    - mt-metadata
    - mth5
    - numpy
    - pyevtk
    - pyproj
    - python >=3.8
    - rasterio
    - scipy
    - simpeg >=0.22.0
    - aurora >=0.3.13
    - xarray >=2025

test:
  imports:
    - mtpy
    - mtpy.core.mt
    - mtpy.core.mt_collection
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MTgeophysics/mtpy-v2
  summary: Python toolkit for standard magnetotelluric data processing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
