{% set name = "mtpy-v2" %}
{% set version = "2.0.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mtpy-v2-{{ version }}.tar.gz
  sha256: 8465904c7473f94ca80513a87d8585ce9f8daf0825103de01c75edd2d739fa1d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8
  run:
    - configparser
    - contextily
    - geopandas
    - matplotlib-base
    - mt-metadata
    - mth5
    - numpy
    - pyevtk
    - pyproj
    - python >=3.8
    - rasterio
    - scipy
    - simpeg >=0.22.0
    - aurora >=0.3.13

test:
  imports:
    - mtpy
    - mtpy.core.mt
    - mtpy.core.mt_collection
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MTgeophysics/mtpy-v2
  summary: Python toolkit for standard magnetotelluric data processing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
