{% set name = "mtpy-v2" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mtpy-v2-{{ version }}.tar.gz
  sha256: 02f1b162a0b028e14526e6cd78fe64b5109124ea3a80c469205ec13517ba82e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pytest-runner
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base <=3.5.3
    - pyproj
    - configparser
    - mt-metadata
    - mth5
    - pandas
    - geopandas
    - contextily
    - pyevtk
    - loguru

test:
  imports:
    - mtpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MTgeophysics/mtpy-v2
  summary: Python toolkit for standard magnetotelluric data processing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
